// Server-side opaque sync storage. The server authenticates accounts but never receives
// notes, labels, images, tombstones, or any decryptable user payload.
import Database from 'better-sqlite3';
import { env } from '$env/dynamic/private';
import { accessSync, constants, existsSync, mkdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

/** `slot` is an opaque, keyed identifier generated by the client for a logical record.
 * It lets the relay replace an old ciphertext without learning whether it is a note, image, etc. */
export type EncryptedEnvelope = { seq: number; id: string; ciphertext: string; slot: string };
export type OpaqueUpload = Omit<EncryptedEnvelope, 'seq'>;
export type OpaqueDelete = { id: string; slot: string };

export type SyncResult = {
	cursor: number;
	envelopes: EncryptedEnvelope[];
	hasMore: boolean;
	reset: boolean;
};

export type SyncStoreOptions = {
	maxAccountBytes?: number;
	maxAccountEnvelopes?: number;
};

type AccountRow = {
	credential_hash: string;
	next_seq: number;
	envelope_count: number;
	ciphertext_bytes: number;
};

type UsageRow = {
	envelopeCount: number;
	ciphertextBytes: number;
};

type LegacyUser = {
	credentialHash?: unknown;
	envelopes?: unknown;
	nextSeq?: unknown;
	updatedAt?: unknown;
};

const DEFAULT_MAX_ACCOUNT_BYTES = 1_000_000_000;
const DEFAULT_MAX_ACCOUNT_ENVELOPES = 50_000;
export const MAX_PUSH_DEVICES = 32;
export const MAX_WAKES_PER_ACCOUNT = 1_000;
export const WAKE_RETAIN_MS = 24 * 60 * 60 * 1000;
export const WAKE_CLAIM_LEASE_MS = 60_000;

export type PushDeviceInput = {
	deviceId: string;
	endpoint: string;
	p256dh: string;
	auth: string;
	accountId: string;
};

export type DueWake = {
	accountId: string;
	deviceId: string;
	wakeId: string;
	fireAt: number;
	endpoint: string;
	p256dh: string;
	auth: string;
};

export type ReminderWakeInput = { id: string; fireAt: number };

const LEGACY_MIGRATION_KEY = 'legacy-users-json-v1';
const USAGE_MIGRATION_KEY = 'account-usage-counters-v1';

export class SyncQuotaExceededError extends Error {
	constructor() {
		super('Sync account storage quota exceeded');
		this.name = 'SyncQuotaExceededError';
	}
}

function positiveInteger(value: string | undefined, fallback: number): number {
	const parsed = Number(value);
	return Number.isSafeInteger(parsed) && parsed > 0 ? parsed : fallback;
}

function isLegacyEnvelope(value: unknown): value is EncryptedEnvelope {
	if (!value || typeof value !== 'object') return false;
	const envelope = value as Partial<EncryptedEnvelope>;
	return (
		Number.isSafeInteger(envelope.seq) &&
		Number(envelope.seq) > 0 &&
		typeof envelope.id === 'string' &&
		typeof envelope.slot === 'string' &&
		typeof envelope.ciphertext === 'string'
	);
}

export class SyncStore {
	private readonly database: Database.Database;
	private readonly dataDirectory: string;
	private readonly maxAccountBytes: number;
	private readonly maxAccountEnvelopes: number;

	constructor(dataDirectory: string, options: SyncStoreOptions = {}) {
		mkdirSync(dataDirectory, { recursive: true });
		this.dataDirectory = dataDirectory;
		this.database = new Database(join(dataDirectory, 'sync.sqlite'));
		this.maxAccountBytes = options.maxAccountBytes ?? DEFAULT_MAX_ACCOUNT_BYTES;
		this.maxAccountEnvelopes = options.maxAccountEnvelopes ?? DEFAULT_MAX_ACCOUNT_ENVELOPES;

		this.database.pragma('journal_mode = WAL');
		this.database.pragma('foreign_keys = ON');
		this.database.pragma('busy_timeout = 5000');
		this.database.exec(`
			CREATE TABLE IF NOT EXISTS meta (
				key TEXT PRIMARY KEY,
				value TEXT NOT NULL
			);
			CREATE TABLE IF NOT EXISTS accounts (
				account_id TEXT PRIMARY KEY,
				credential_hash TEXT NOT NULL,
				next_seq INTEGER NOT NULL DEFAULT 0,
				envelope_count INTEGER NOT NULL DEFAULT 0,
				ciphertext_bytes INTEGER NOT NULL DEFAULT 0,
				updated_at INTEGER NOT NULL
			);
			CREATE TABLE IF NOT EXISTS envelopes (
				account_id TEXT NOT NULL,
				slot TEXT NOT NULL,
				seq INTEGER NOT NULL,
				id TEXT NOT NULL,
				ciphertext TEXT NOT NULL,
				PRIMARY KEY (account_id, slot),
				UNIQUE (account_id, id),
				FOREIGN KEY (account_id) REFERENCES accounts(account_id) ON DELETE CASCADE
			);
			CREATE INDEX IF NOT EXISTS envelopes_account_seq
				ON envelopes(account_id, seq);
			CREATE TABLE IF NOT EXISTS reminder_push_devices (
				account_id TEXT NOT NULL,
				device_id TEXT NOT NULL,
				endpoint TEXT NOT NULL UNIQUE,
				p256dh TEXT NOT NULL,
				auth TEXT NOT NULL,
				updated_at INTEGER NOT NULL,
				PRIMARY KEY (account_id, device_id),
				FOREIGN KEY (account_id) REFERENCES accounts(account_id) ON DELETE CASCADE
			);
			CREATE INDEX IF NOT EXISTS reminder_push_devices_device
				ON reminder_push_devices(device_id);
			CREATE TABLE IF NOT EXISTS reminder_wakes_v2 (
				account_id TEXT NOT NULL,
				wake_id TEXT NOT NULL,
				fire_at INTEGER NOT NULL,
				PRIMARY KEY (account_id, wake_id),
				FOREIGN KEY (account_id) REFERENCES accounts(account_id) ON DELETE CASCADE
			);
			CREATE INDEX IF NOT EXISTS reminder_wakes_v2_due ON reminder_wakes_v2(fire_at);
			CREATE TABLE IF NOT EXISTS reminder_wake_deliveries (
				account_id TEXT NOT NULL,
				device_id TEXT NOT NULL,
				wake_id TEXT NOT NULL,
				claimed_at INTEGER NOT NULL,
				delivered_at INTEGER,
				PRIMARY KEY (account_id, device_id, wake_id),
				FOREIGN KEY (account_id) REFERENCES accounts(account_id) ON DELETE CASCADE
			);
		`);
		this.database.exec(`
			DROP TABLE IF EXISTS wake_deliveries;
			DROP TABLE IF EXISTS account_wakes;
			DROP TABLE IF EXISTS push_devices;
			DROP TABLE IF EXISTS push_wakes;
			DROP TABLE IF EXISTS reminder_wakes;
			DROP TABLE IF EXISTS push_subscriptions;
		`);
		this.ensureUsageColumns();
		this.migrateLegacyJson(join(dataDirectory, 'users.json'));
		this.migrateUsageCounters();
	}

	close(): void {
		this.database.close();
	}

	async backup(destination: string): Promise<void> {
		await this.database.backup(destination);
	}

	getCredentialHash(accountId: string): string | null {
		const row = this.database
			.prepare('SELECT credential_hash FROM accounts WHERE account_id = ?')
			.get(accountId) as Pick<AccountRow, 'credential_hash'> | undefined;
		return row?.credential_hash ?? null;
	}

	createAccount(accountId: string, credentialHash: string, updatedAt = Date.now()): boolean {
		const result = this.database
			.prepare(
				`
			INSERT OR IGNORE INTO accounts(
				account_id, credential_hash, next_seq, envelope_count, ciphertext_bytes, updated_at
			)
			VALUES (?, ?, 0, 0, 0, ?)
		`
			)
			.run(accountId, credentialHash, updatedAt);
		return result.changes === 1;
	}

	sync(
		accountId: string,
		cursor: number,
		uploads: OpaqueUpload[],
		deletionsOrLimit: OpaqueDelete[] | number,
		requestedDownloadLimit?: number
	): SyncResult & { usage: UsageRow & { maxBytes: number; maxEnvelopes: number } } {
		const deletions = Array.isArray(deletionsOrLimit) ? deletionsOrLimit : [];
		const downloadLimit = Array.isArray(deletionsOrLimit)
			? (requestedDownloadLimit ?? 12)
			: deletionsOrLimit;
		return this.database.transaction(() => {
			const account = this.database
				.prepare(
					`
				SELECT credential_hash, next_seq, envelope_count, ciphertext_bytes
				FROM accounts
				WHERE account_id = ?
			`
				)
				.get(accountId) as AccountRow | undefined;
			if (!account) throw new Error('Sync account does not exist');

			let envelopeCount = account.envelope_count;
			let ciphertextBytes = account.ciphertext_bytes;
			const remove = this.database.prepare(`
				DELETE FROM envelopes
				WHERE account_id = ? AND slot = ? AND id = ?
				RETURNING length(ciphertext) AS ciphertext_bytes
			`);
			for (const deletion of deletions) {
				const removed = remove.get(accountId, deletion.slot, deletion.id) as
					{ ciphertext_bytes: number } | undefined;
				if (!removed) continue;
				envelopeCount -= 1;
				ciphertextBytes -= removed.ciphertext_bytes;
			}

			const page = this.database
				.prepare(
					`
				SELECT seq, id, ciphertext, slot
				FROM envelopes
				WHERE account_id = ? AND seq > ?
				ORDER BY seq ASC
				LIMIT ?
			`
				)
				.all(accountId, cursor, downloadLimit + 1) as EncryptedEnvelope[];
			const hasMore = page.length > downloadLimit;
			const remote = hasMore ? page.slice(0, downloadLimit) : page;
			let sequence = account.next_seq;
			let added = false;

			const hasId = this.database.prepare(
				'SELECT 1 FROM envelopes WHERE account_id = ? AND id = ?'
			);
			const priorSlot = this.database.prepare(
				'SELECT length(ciphertext) AS ciphertext_bytes FROM envelopes WHERE account_id = ? AND slot = ?'
			);
			const upsert = this.database.prepare(`
				INSERT INTO envelopes(account_id, slot, seq, id, ciphertext)
				VALUES (?, ?, ?, ?, ?)
				ON CONFLICT(account_id, slot) DO UPDATE SET
					seq = excluded.seq,
					id = excluded.id,
					ciphertext = excluded.ciphertext
			`);

			for (const upload of uploads) {
				if (hasId.get(accountId, upload.id)) continue;
				const prior = priorSlot.get(accountId, upload.slot) as
					{ ciphertext_bytes: number } | undefined;
				const projectedCount = envelopeCount + (prior ? 0 : 1);
				const projectedBytes =
					ciphertextBytes + upload.ciphertext.length - (prior?.ciphertext_bytes ?? 0);
				if (projectedCount > this.maxAccountEnvelopes || projectedBytes > this.maxAccountBytes) {
					throw new SyncQuotaExceededError();
				}
				sequence += 1;
				upsert.run(accountId, upload.slot, sequence, upload.id, upload.ciphertext);
				envelopeCount = projectedCount;
				ciphertextBytes = projectedBytes;
				added = true;
			}

			if (added || deletions.length > 0) {
				this.database
					.prepare(
						`
					UPDATE accounts
					SET next_seq = ?, envelope_count = ?, ciphertext_bytes = ?, updated_at = ?
					WHERE account_id = ?
				`
					)
					.run(sequence, envelopeCount, ciphertextBytes, Date.now(), accountId);
			}

			const afterRemote = remote.at(-1)?.seq ?? cursor;
			// Do not jump over an undisclosed download page just because this request
			// also uploaded a newer sequence.
			const nextCursor = hasMore
				? afterRemote
				: Math.max(afterRemote, added ? sequence : afterRemote);
			return {
				cursor: nextCursor,
				envelopes: remote,
				hasMore,
				reset: envelopeCount === 0 && cursor > 0,
				usage: {
					envelopeCount,
					ciphertextBytes,
					maxBytes: this.maxAccountBytes,
					maxEnvelopes: this.maxAccountEnvelopes
				}
			};
		})();
	}

	deleteAccount(accountId: string): boolean {
		return (
			this.database.prepare('DELETE FROM accounts WHERE account_id = ?').run(accountId).changes ===
			1
		);
	}

	getMeta(key: string): string | null {
		const row = this.database.prepare('SELECT value FROM meta WHERE key = ?').get(key) as
			{ value: string } | undefined;
		return row?.value ?? null;
	}

	setMeta(key: string, value: string): void {
		this.database
			.prepare(
				`
			INSERT INTO meta(key, value) VALUES (?, ?)
			ON CONFLICT(key) DO UPDATE SET value = excluded.value
		`
			)
			.run(key, value);
	}

	/** Register one account-scoped browser endpoint without changing account wakes. */
	savePushDevice(device: PushDeviceInput): void {
		this.database.transaction(() => {
			const existing = this.database
				.prepare(
					'SELECT 1 AS present FROM reminder_push_devices WHERE account_id = ? AND device_id = ?'
				)
				.get(device.accountId, device.deviceId) as { present: number } | undefined;

			this.database
				.prepare(
					'DELETE FROM reminder_push_devices WHERE endpoint = ? AND (account_id != ? OR device_id != ?)'
				)
				.run(device.endpoint, device.accountId, device.deviceId);
			this.database
				.prepare('DELETE FROM reminder_push_devices WHERE device_id = ? AND account_id != ?')
				.run(device.deviceId, device.accountId);

			if (!existing) {
				const extras = this.database
					.prepare(
						'SELECT device_id FROM reminder_push_devices WHERE account_id = ? ORDER BY updated_at ASC'
					)
					.all(device.accountId) as Array<{ device_id: string }>;
				const overflow = extras.length + 1 - MAX_PUSH_DEVICES;
				if (overflow > 0) {
					const removeDevice = this.database.prepare(
						'DELETE FROM reminder_push_devices WHERE account_id = ? AND device_id = ?'
					);
					for (const row of extras.slice(0, overflow)) {
						removeDevice.run(device.accountId, row.device_id);
					}
				}
			}

			this.database
				.prepare(
					`
				INSERT INTO reminder_push_devices(
					account_id, device_id, endpoint, p256dh, auth, updated_at
				)
				VALUES (?, ?, ?, ?, ?, ?)
				ON CONFLICT(account_id, device_id) DO UPDATE SET
					endpoint = excluded.endpoint,
					p256dh = excluded.p256dh,
					auth = excluded.auth,
					updated_at = excluded.updated_at
			`
				)
				.run(
					device.accountId,
					device.deviceId,
					device.endpoint,
					device.p256dh,
					device.auth,
					Date.now()
				);
		})();
	}

	replaceReminderWakes(accountId: string, wakes: ReminderWakeInput[]): void {
		this.database.transaction(() => {
			this.database.prepare('DELETE FROM reminder_wakes_v2 WHERE account_id = ?').run(accountId);
			const insert = this.database.prepare(
				'INSERT INTO reminder_wakes_v2(account_id, wake_id, fire_at) VALUES (?, ?, ?)'
			);
			for (const wake of wakes.slice(0, MAX_WAKES_PER_ACCOUNT)) {
				insert.run(accountId, wake.id, wake.fireAt);
			}
			this.database
				.prepare(
					`DELETE FROM reminder_wake_deliveries
					 WHERE account_id = ? AND NOT EXISTS (
						SELECT 1 FROM reminder_wakes_v2 w
						WHERE w.account_id = reminder_wake_deliveries.account_id
							AND w.wake_id = reminder_wake_deliveries.wake_id
					)`
				)
				.run(accountId);
		})();
	}

	claimDueWakes(now: number, limit = 100): DueWake[] {
		return this.database
			.transaction(() => {
				const rows = this.database
					.prepare(
						`SELECT
						d.account_id AS accountId,
						d.device_id AS deviceId,
						w.wake_id AS wakeId,
						w.fire_at AS fireAt,
						d.endpoint AS endpoint,
						d.p256dh AS p256dh,
						d.auth AS auth
					 FROM reminder_wakes_v2 w
					 INNER JOIN reminder_push_devices d ON d.account_id = w.account_id
					 LEFT JOIN reminder_wake_deliveries x
						ON x.account_id = d.account_id
						AND x.device_id = d.device_id
						AND x.wake_id = w.wake_id
					 WHERE w.fire_at <= ?
						AND x.delivered_at IS NULL
						AND (x.claimed_at IS NULL OR x.claimed_at <= ?)
					 ORDER BY w.fire_at ASC, w.wake_id ASC, d.device_id ASC
					 LIMIT ?`
					)
					.all(now, now - WAKE_CLAIM_LEASE_MS, limit) as DueWake[];
				const claim = this.database.prepare(
					`INSERT INTO reminder_wake_deliveries(
					account_id, device_id, wake_id, claimed_at, delivered_at
				 ) VALUES (?, ?, ?, ?, NULL)
				 ON CONFLICT(account_id, device_id, wake_id) DO UPDATE SET
					claimed_at = excluded.claimed_at,
					delivered_at = NULL`
				);
				for (const row of rows) claim.run(row.accountId, row.deviceId, row.wakeId, now);
				return rows;
			})
			.immediate();
	}

	markWakeDelivered(wake: Pick<DueWake, 'accountId' | 'deviceId' | 'wakeId'>, now: number): void {
		this.database
			.prepare(
				`UPDATE reminder_wake_deliveries SET delivered_at = ?
				 WHERE account_id = ? AND device_id = ? AND wake_id = ?`
			)
			.run(now, wake.accountId, wake.deviceId, wake.wakeId);
	}

	releaseWakeClaim(wake: Pick<DueWake, 'accountId' | 'deviceId' | 'wakeId'>): void {
		this.database
			.prepare(
				`DELETE FROM reminder_wake_deliveries
				 WHERE account_id = ? AND device_id = ? AND wake_id = ? AND delivered_at IS NULL`
			)
			.run(wake.accountId, wake.deviceId, wake.wakeId);
	}

	pruneStaleWakes(now: number, retainMs = WAKE_RETAIN_MS): void {
		const cutoff = now - retainMs;
		this.database.transaction(() => {
			this.database.prepare('DELETE FROM reminder_wakes_v2 WHERE fire_at < ?').run(cutoff);
			this.database
				.prepare(
					`DELETE FROM reminder_wake_deliveries WHERE NOT EXISTS (
						SELECT 1 FROM reminder_wakes_v2 w
						WHERE w.account_id = reminder_wake_deliveries.account_id
							AND w.wake_id = reminder_wake_deliveries.wake_id
					)`
				)
				.run();
		})();
	}

	deletePushDevice(accountId: string, deviceId: string): void {
		this.database
			.prepare('DELETE FROM reminder_push_devices WHERE account_id = ? AND device_id = ?')
			.run(accountId, deviceId);
	}

	nextWakeAt(now = Date.now()): number | null {
		const due = this.database
			.prepare(
				`SELECT 1 AS present FROM reminder_wakes_v2 w
				 INNER JOIN reminder_push_devices d ON d.account_id = w.account_id
				 LEFT JOIN reminder_wake_deliveries x
					ON x.account_id = d.account_id AND x.device_id = d.device_id AND x.wake_id = w.wake_id
				 WHERE w.fire_at <= ? AND x.delivered_at IS NULL
					AND (x.claimed_at IS NULL OR x.claimed_at <= ?)
				 LIMIT 1`
			)
			.get(now, now - WAKE_CLAIM_LEASE_MS) as { present: number } | undefined;
		if (due) return now;
		const row = this.database
			.prepare('SELECT MIN(fire_at) AS fireAt FROM reminder_wakes_v2 WHERE fire_at > ?')
			.get(now) as { fireAt: number | null } | undefined;
		return row?.fireAt ?? null;
	}

	countPushDevices(accountId?: string): number {
		const row = (
			accountId
				? this.database
						.prepare('SELECT COUNT(*) AS count FROM reminder_push_devices WHERE account_id = ?')
						.get(accountId)
				: this.database.prepare('SELECT COUNT(*) AS count FROM reminder_push_devices').get()
		) as {
			count: number;
		};
		return row.count;
	}

	listWakeTimes(accountId: string): number[] {
		const rows = this.database
			.prepare(
				`SELECT fire_at AS fireAt FROM reminder_wakes_v2
				 WHERE account_id = ? ORDER BY fire_at ASC, wake_id ASC`
			)
			.all(accountId) as Array<{ fireAt: number }>;
		return rows.map((row) => row.fireAt);
	}

	isReady(): boolean {
		try {
			accessSync(this.dataDirectory, constants.W_OK);
			const migrations = this.database
				.prepare('SELECT COUNT(*) AS count FROM meta WHERE key IN (?, ?)')
				.get(LEGACY_MIGRATION_KEY, USAGE_MIGRATION_KEY) as { count: number };
			return (
				(this.database.prepare('SELECT 1 AS ready').get() as { ready: number }).ready === 1 &&
				migrations.count === 2
			);
		} catch {
			return false;
		}
	}

	aggregateUsage(): UsageRow & { accounts: number } {
		return this.database
			.prepare(
				`
			SELECT
				COUNT(*) AS accounts,
				COALESCE(SUM(envelope_count), 0) AS envelopeCount,
				COALESCE(SUM(ciphertext_bytes), 0) AS ciphertextBytes
			FROM accounts
		`
			)
			.get() as UsageRow & { accounts: number };
	}

	private ensureUsageColumns(): void {
		const columns = new Set(
			(this.database.prepare('PRAGMA table_info(accounts)').all() as Array<{ name: string }>).map(
				(column) => column.name
			)
		);
		if (!columns.has('envelope_count')) {
			this.database.exec(
				'ALTER TABLE accounts ADD COLUMN envelope_count INTEGER NOT NULL DEFAULT 0'
			);
		}
		if (!columns.has('ciphertext_bytes')) {
			this.database.exec(
				'ALTER TABLE accounts ADD COLUMN ciphertext_bytes INTEGER NOT NULL DEFAULT 0'
			);
		}
	}

	private migrateUsageCounters(): void {
		if (this.database.prepare('SELECT 1 FROM meta WHERE key = ?').get(USAGE_MIGRATION_KEY)) return;
		this.database.transaction(() => {
			this.database.exec(`
				UPDATE accounts
				SET envelope_count = (
					SELECT COUNT(*) FROM envelopes WHERE envelopes.account_id = accounts.account_id
				),
				ciphertext_bytes = (
					SELECT COALESCE(SUM(length(ciphertext)), 0)
					FROM envelopes
					WHERE envelopes.account_id = accounts.account_id
				)
			`);
			this.database
				.prepare('INSERT INTO meta(key, value) VALUES (?, ?)')
				.run(USAGE_MIGRATION_KEY, String(Date.now()));
		})();
	}

	private migrateLegacyJson(file: string): void {
		const migrated = this.database
			.prepare('SELECT 1 FROM meta WHERE key = ?')
			.get(LEGACY_MIGRATION_KEY);
		if (migrated) return;

		this.database.transaction(() => {
			if (existsSync(file)) {
				const parsed: unknown = JSON.parse(readFileSync(file, 'utf8'));
				if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
					throw new Error('Legacy sync data file is not a JSON object');
				}
				const insertAccount = this.database.prepare(`
					INSERT OR IGNORE INTO accounts(
						account_id, credential_hash, next_seq, envelope_count, ciphertext_bytes, updated_at
					)
					VALUES (?, ?, ?, 0, 0, ?)
				`);
				const insertEnvelope = this.database.prepare(`
					INSERT OR REPLACE INTO envelopes(account_id, slot, seq, id, ciphertext)
					VALUES (?, ?, ?, ?, ?)
				`);
				for (const [accountId, rawUser] of Object.entries(parsed)) {
					if (!rawUser || typeof rawUser !== 'object') continue;
					const user = rawUser as LegacyUser;
					if (typeof user.credentialHash !== 'string') continue;
					const envelopes = Array.isArray(user.envelopes)
						? user.envelopes.filter(isLegacyEnvelope).sort((a, b) => a.seq - b.seq)
						: [];
					const maxSequence = Math.max(
						Number.isSafeInteger(user.nextSeq) ? Number(user.nextSeq) : 0,
						...envelopes.map((envelope) => envelope.seq),
						0
					);
					insertAccount.run(
						accountId,
						user.credentialHash,
						maxSequence,
						Number(user.updatedAt) || Date.now()
					);
					for (const envelope of envelopes) {
						insertEnvelope.run(
							accountId,
							envelope.slot,
							envelope.seq,
							envelope.id,
							envelope.ciphertext
						);
					}
				}
			}
			this.database
				.prepare('INSERT INTO meta(key, value) VALUES (?, ?)')
				.run(LEGACY_MIGRATION_KEY, String(Date.now()));
		})();
	}
}

let singleton: SyncStore | undefined;

export function getSyncStore(): SyncStore {
	singleton ??= new SyncStore(env.SCRAPS_CACHE_SYNC_DATA_DIR || 'sync-data', {
		maxAccountBytes: positiveInteger(
			env.SCRAPS_CACHE_SYNC_MAX_ACCOUNT_BYTES,
			DEFAULT_MAX_ACCOUNT_BYTES
		),
		maxAccountEnvelopes: positiveInteger(
			env.SCRAPS_CACHE_SYNC_MAX_ACCOUNT_ENVELOPES,
			DEFAULT_MAX_ACCOUNT_ENVELOPES
		)
	});
	return singleton;
}

export function closeSyncStore(): void {
	singleton?.close();
	singleton = undefined;
}
