// Server-side opaque sync storage. The server authenticates accounts but never receives
// notes, labels, images, tombstones, or any decryptable user payload.
import Database from 'better-sqlite3';
import { env } from '$env/dynamic/private';
import { accessSync, constants, existsSync, mkdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

/** `slot` is an opaque, keyed identifier generated by the client for a logical record.
 * It lets the relay replace an old ciphertext without learning whether it is a note, image, etc. */
export type EncryptedEnvelope = { seq: number; id: string; ciphertext: string; slot: string };
export type OpaqueUpload = Omit<EncryptedEnvelope, 'seq'>;
export type OpaqueDelete = { id: string; slot: string };

export type SyncResult = {
	cursor: number;
	envelopes: EncryptedEnvelope[];
	hasMore: boolean;
	reset: boolean;
};

export type SyncStoreOptions = {
	maxAccountBytes?: number;
	maxAccountEnvelopes?: number;
};

type AccountRow = {
	credential_hash: string;
	next_seq: number;
	envelope_count: number;
	ciphertext_bytes: number;
};

type UsageRow = {
	envelopeCount: number;
	ciphertextBytes: number;
};

type LegacyUser = {
	credentialHash?: unknown;
	envelopes?: unknown;
	nextSeq?: unknown;
	updatedAt?: unknown;
};

const DEFAULT_MAX_ACCOUNT_BYTES = 1_000_000_000;
const DEFAULT_MAX_ACCOUNT_ENVELOPES = 50_000;
const LEGACY_MIGRATION_KEY = 'legacy-users-json-v1';
const USAGE_MIGRATION_KEY = 'account-usage-counters-v1';

export class SyncQuotaExceededError extends Error {
	constructor() {
		super('Sync account storage quota exceeded');
		this.name = 'SyncQuotaExceededError';
	}
}

function positiveInteger(value: string | undefined, fallback: number): number {
	const parsed = Number(value);
	return Number.isSafeInteger(parsed) && parsed > 0 ? parsed : fallback;
}

function isLegacyEnvelope(value: unknown): value is EncryptedEnvelope {
	if (!value || typeof value !== 'object') return false;
	const envelope = value as Partial<EncryptedEnvelope>;
	return Number.isSafeInteger(envelope.seq)
		&& Number(envelope.seq) > 0
		&& typeof envelope.id === 'string'
		&& typeof envelope.slot === 'string'
		&& typeof envelope.ciphertext === 'string';
}

export class SyncStore {
	private readonly database: Database.Database;
	private readonly dataDirectory: string;
	private readonly maxAccountBytes: number;
	private readonly maxAccountEnvelopes: number;

	constructor(dataDirectory: string, options: SyncStoreOptions = {}) {
		mkdirSync(dataDirectory, { recursive: true });
		this.dataDirectory = dataDirectory;
		this.database = new Database(join(dataDirectory, 'sync.sqlite'));
		this.maxAccountBytes = options.maxAccountBytes ?? DEFAULT_MAX_ACCOUNT_BYTES;
		this.maxAccountEnvelopes = options.maxAccountEnvelopes ?? DEFAULT_MAX_ACCOUNT_ENVELOPES;

		this.database.pragma('journal_mode = WAL');
		this.database.pragma('foreign_keys = ON');
		this.database.pragma('busy_timeout = 5000');
		this.database.exec(`
			CREATE TABLE IF NOT EXISTS meta (
				key TEXT PRIMARY KEY,
				value TEXT NOT NULL
			);
			CREATE TABLE IF NOT EXISTS accounts (
				account_id TEXT PRIMARY KEY,
				credential_hash TEXT NOT NULL,
				next_seq INTEGER NOT NULL DEFAULT 0,
				envelope_count INTEGER NOT NULL DEFAULT 0,
				ciphertext_bytes INTEGER NOT NULL DEFAULT 0,
				updated_at INTEGER NOT NULL
			);
			CREATE TABLE IF NOT EXISTS envelopes (
				account_id TEXT NOT NULL,
				slot TEXT NOT NULL,
				seq INTEGER NOT NULL,
				id TEXT NOT NULL,
				ciphertext TEXT NOT NULL,
				PRIMARY KEY (account_id, slot),
				UNIQUE (account_id, id),
				FOREIGN KEY (account_id) REFERENCES accounts(account_id) ON DELETE CASCADE
			);
			CREATE INDEX IF NOT EXISTS envelopes_account_seq
				ON envelopes(account_id, seq);
		`);
		this.ensureUsageColumns();
		this.migrateLegacyJson(join(dataDirectory, 'users.json'));
		this.migrateUsageCounters();
	}

	close(): void {
		this.database.close();
	}

	async backup(destination: string): Promise<void> {
		await this.database.backup(destination);
	}

	getCredentialHash(accountId: string): string | null {
		const row = this.database.prepare(
			'SELECT credential_hash FROM accounts WHERE account_id = ?'
		).get(accountId) as Pick<AccountRow, 'credential_hash'> | undefined;
		return row?.credential_hash ?? null;
	}

	createAccount(accountId: string, credentialHash: string, updatedAt = Date.now()): boolean {
		const result = this.database.prepare(`
			INSERT OR IGNORE INTO accounts(
				account_id, credential_hash, next_seq, envelope_count, ciphertext_bytes, updated_at
			)
			VALUES (?, ?, 0, 0, 0, ?)
		`).run(accountId, credentialHash, updatedAt);
		return result.changes === 1;
	}

	sync(
		accountId: string,
		cursor: number,
		uploads: OpaqueUpload[],
		deletionsOrLimit: OpaqueDelete[] | number,
		requestedDownloadLimit?: number
	): SyncResult & { usage: UsageRow & { maxBytes: number; maxEnvelopes: number } } {
		const deletions = Array.isArray(deletionsOrLimit) ? deletionsOrLimit : [];
		const downloadLimit = Array.isArray(deletionsOrLimit)
			? (requestedDownloadLimit ?? 12)
			: deletionsOrLimit;
		return this.database.transaction(() => {
			const account = this.database.prepare(`
				SELECT credential_hash, next_seq, envelope_count, ciphertext_bytes
				FROM accounts
				WHERE account_id = ?
			`).get(accountId) as AccountRow | undefined;
			if (!account) throw new Error('Sync account does not exist');

			let envelopeCount = account.envelope_count;
			let ciphertextBytes = account.ciphertext_bytes;
			const remove = this.database.prepare(`
				DELETE FROM envelopes
				WHERE account_id = ? AND slot = ? AND id = ?
				RETURNING length(ciphertext) AS ciphertext_bytes
			`);
			for (const deletion of deletions) {
				const removed = remove.get(accountId, deletion.slot, deletion.id) as
					| { ciphertext_bytes: number }
					| undefined;
				if (!removed) continue;
				envelopeCount -= 1;
				ciphertextBytes -= removed.ciphertext_bytes;
			}

			const page = this.database.prepare(`
				SELECT seq, id, ciphertext, slot
				FROM envelopes
				WHERE account_id = ? AND seq > ?
				ORDER BY seq ASC
				LIMIT ?
			`).all(accountId, cursor, downloadLimit + 1) as EncryptedEnvelope[];
			const hasMore = page.length > downloadLimit;
			const remote = hasMore ? page.slice(0, downloadLimit) : page;
			let sequence = account.next_seq;
			let added = false;

			const hasId = this.database.prepare(
				'SELECT 1 FROM envelopes WHERE account_id = ? AND id = ?'
			);
			const priorSlot = this.database.prepare(
				'SELECT length(ciphertext) AS ciphertext_bytes FROM envelopes WHERE account_id = ? AND slot = ?'
			);
			const upsert = this.database.prepare(`
				INSERT INTO envelopes(account_id, slot, seq, id, ciphertext)
				VALUES (?, ?, ?, ?, ?)
				ON CONFLICT(account_id, slot) DO UPDATE SET
					seq = excluded.seq,
					id = excluded.id,
					ciphertext = excluded.ciphertext
			`);

			for (const upload of uploads) {
				if (hasId.get(accountId, upload.id)) continue;
				const prior = priorSlot.get(accountId, upload.slot) as
					| { ciphertext_bytes: number }
					| undefined;
				const projectedCount = envelopeCount + (prior ? 0 : 1);
				const projectedBytes = ciphertextBytes + upload.ciphertext.length
					- (prior?.ciphertext_bytes ?? 0);
				if (projectedCount > this.maxAccountEnvelopes
					|| projectedBytes > this.maxAccountBytes) {
					throw new SyncQuotaExceededError();
				}
				sequence += 1;
				upsert.run(accountId, upload.slot, sequence, upload.id, upload.ciphertext);
				envelopeCount = projectedCount;
				ciphertextBytes = projectedBytes;
				added = true;
			}

			if (added || deletions.length > 0) {
				this.database.prepare(`
					UPDATE accounts
					SET next_seq = ?, envelope_count = ?, ciphertext_bytes = ?, updated_at = ?
					WHERE account_id = ?
				`).run(sequence, envelopeCount, ciphertextBytes, Date.now(), accountId);
			}

			const afterRemote = remote.at(-1)?.seq ?? cursor;
			// Do not jump over an undisclosed download page just because this request
			// also uploaded a newer sequence.
			const nextCursor = hasMore
				? afterRemote
				: Math.max(afterRemote, added ? sequence : afterRemote);
			return {
				cursor: nextCursor,
				envelopes: remote,
				hasMore,
				reset: envelopeCount === 0 && cursor > 0,
				usage: {
					envelopeCount,
					ciphertextBytes,
					maxBytes: this.maxAccountBytes,
					maxEnvelopes: this.maxAccountEnvelopes
				}
			};
		})();
	}

	deleteAccount(accountId: string): boolean {
		return this.database.prepare('DELETE FROM accounts WHERE account_id = ?').run(accountId).changes === 1;
	}

	isReady(): boolean {
		try {
			accessSync(this.dataDirectory, constants.W_OK);
			const migrations = this.database.prepare(
				'SELECT COUNT(*) AS count FROM meta WHERE key IN (?, ?)'
			).get(LEGACY_MIGRATION_KEY, USAGE_MIGRATION_KEY) as { count: number };
			return (this.database.prepare('SELECT 1 AS ready').get() as { ready: number }).ready === 1
				&& migrations.count === 2;
		} catch {
			return false;
		}
	}

	aggregateUsage(): UsageRow & { accounts: number } {
		return this.database.prepare(`
			SELECT
				COUNT(*) AS accounts,
				COALESCE(SUM(envelope_count), 0) AS envelopeCount,
				COALESCE(SUM(ciphertext_bytes), 0) AS ciphertextBytes
			FROM accounts
		`).get() as UsageRow & { accounts: number };
	}

	private ensureUsageColumns(): void {
		const columns = new Set(
			(this.database.prepare('PRAGMA table_info(accounts)').all() as Array<{ name: string }>)
				.map((column) => column.name)
		);
		if (!columns.has('envelope_count')) {
			this.database.exec('ALTER TABLE accounts ADD COLUMN envelope_count INTEGER NOT NULL DEFAULT 0');
		}
		if (!columns.has('ciphertext_bytes')) {
			this.database.exec('ALTER TABLE accounts ADD COLUMN ciphertext_bytes INTEGER NOT NULL DEFAULT 0');
		}
	}

	private migrateUsageCounters(): void {
		if (this.database.prepare('SELECT 1 FROM meta WHERE key = ?').get(USAGE_MIGRATION_KEY)) return;
		this.database.transaction(() => {
			this.database.exec(`
				UPDATE accounts
				SET envelope_count = (
					SELECT COUNT(*) FROM envelopes WHERE envelopes.account_id = accounts.account_id
				),
				ciphertext_bytes = (
					SELECT COALESCE(SUM(length(ciphertext)), 0)
					FROM envelopes
					WHERE envelopes.account_id = accounts.account_id
				)
			`);
			this.database.prepare('INSERT INTO meta(key, value) VALUES (?, ?)').run(
				USAGE_MIGRATION_KEY,
				String(Date.now())
			);
		})();
	}

	private migrateLegacyJson(file: string): void {
		const migrated = this.database.prepare('SELECT 1 FROM meta WHERE key = ?').get(LEGACY_MIGRATION_KEY);
		if (migrated) return;

		this.database.transaction(() => {
			if (existsSync(file)) {
				const parsed: unknown = JSON.parse(readFileSync(file, 'utf8'));
				if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
					throw new Error('Legacy sync data file is not a JSON object');
				}
				const insertAccount = this.database.prepare(`
					INSERT OR IGNORE INTO accounts(
						account_id, credential_hash, next_seq, envelope_count, ciphertext_bytes, updated_at
					)
					VALUES (?, ?, ?, 0, 0, ?)
				`);
				const insertEnvelope = this.database.prepare(`
					INSERT OR REPLACE INTO envelopes(account_id, slot, seq, id, ciphertext)
					VALUES (?, ?, ?, ?, ?)
				`);
				for (const [accountId, rawUser] of Object.entries(parsed)) {
					if (!rawUser || typeof rawUser !== 'object') continue;
					const user = rawUser as LegacyUser;
					if (typeof user.credentialHash !== 'string') continue;
					const envelopes = Array.isArray(user.envelopes)
						? user.envelopes.filter(isLegacyEnvelope).sort((a, b) => a.seq - b.seq)
						: [];
					const maxSequence = Math.max(
						Number.isSafeInteger(user.nextSeq) ? Number(user.nextSeq) : 0,
						...envelopes.map((envelope) => envelope.seq),
						0
					);
					insertAccount.run(
						accountId,
						user.credentialHash,
						maxSequence,
						Number(user.updatedAt) || Date.now()
					);
					for (const envelope of envelopes) {
						insertEnvelope.run(
							accountId,
							envelope.slot,
							envelope.seq,
							envelope.id,
							envelope.ciphertext
						);
					}
				}
			}
			this.database.prepare('INSERT INTO meta(key, value) VALUES (?, ?)').run(
				LEGACY_MIGRATION_KEY,
				String(Date.now())
			);
		})();
	}
}

let singleton: SyncStore | undefined;

export function getSyncStore(): SyncStore {
	singleton ??= new SyncStore(env.SHARD_SYNC_DATA_DIR || 'sync-data', {
		maxAccountBytes: positiveInteger(
			env.SHARD_SYNC_MAX_ACCOUNT_BYTES,
			DEFAULT_MAX_ACCOUNT_BYTES
		),
		maxAccountEnvelopes: positiveInteger(
			env.SHARD_SYNC_MAX_ACCOUNT_ENVELOPES,
			DEFAULT_MAX_ACCOUNT_ENVELOPES
		)
	});
	return singleton;
}

export function closeSyncStore(): void {
	singleton?.close();
	singleton = undefined;
}
